--- #YAML:1.0
name:               CatalystX-CRUD-Model-RDBO
version:            0.21
abstract:           ~
author:
    - Peter Karman <karman@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Runtime:    5.8
    CatalystX::CRUD:      0.43
    Data::Dump:           0
    Rose::DB::Object:     0
    Rose::DBx::Object::MoreHelpers:  0
    Rose::DBx::TestDB:    0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
